const cookieParser = require("cookie-parser");
const express = require("express");
const app = express();
var cors = require("cors");
const bodyParser = require("body-parser");
const fileUpload = require("express-fileUpload");
const { errorMiddleware } = require("./middleware/error");
app.use(express.json());
app.use(cookieParser());
app.use(cors());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(fileUpload());
const productRoute = require("./routes/productRoute");
const userRoute = require("./routes/userRoute");
const orderRoute = require("./routes/orderRoute");
app.use("/api/v1", productRoute);
app.use("/api/v1", userRoute);
app.use("/api/v1", orderRoute);
app.use(errorMiddleware);
module.exports = app;